## A basic GitHub Actions workflow for your Quarkus application.

name: CI build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Build
        run: ./mvnw verify -B
        env:
          QUARKUS_DATASOURCE_JDBC_URL: "jdbc:mysql://82.29.155.85:3306/mydb?useTimezone=true&serverTimezone=UTC"
